catalogs:
  framework:
    nuxt: ^4.2.1
    sass-embedded: ^1.93.3
    typescript: ^5.9.3
    vue: ^3.5.24
    vue-router: ^4.6.3
  quality:
    '@antfu/eslint-config': ^6.2.0
    '@zinkawaii/stylelint-config': ^0.3.4
    eslint: ^9.39.1
    stylelint: ^16.25.0
  ui:
    '@nuxt/icon': ^2.1.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
  util:
    '@nuxtjs/seo': ^3.2.2
    '@pinia/nuxt': ^0.11.3
    '@vueuse/core': ^14.0.0
    '@vueuse/nuxt': ^14.0.0
    date-fns: ^4.1.0
    date-fns-tz: ^3.2.0
    fast-xml-parser: ^5.3.2

engineStrict: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

shamefullyHoist: true
